### ISSUE TITLE
Examples of using FS abstraction

### ISSUE THREAD

**Issue by erickpece** [nodeftpd/nodeftpd#116]
This supports Filesystem Abstraction.  Are there any examples of this which can be used to build out integration with SMB or S3?

**Comment by adamdunkley** [comment]
@erickpece Hi. We have just started using nodeftpd with a s3 file abstraction. Our customers only require a dropbox and we'd prefer not to store the files they transfer to disk let alone to memory so the promise of some node streaming magic was too tempting not to try this solution.

The documentation isn't great around how to do this, tbh, but after reading the code I begun to understand the following line in the [fs abstraction](https://github.com/sstur/nodeftpd#filesystem-abstraction) section of the readme: "On successful login, success should be called with a username argument. It may also optionally be given a second argument, which should be an object providing an implementation of the API for Node's fs module."

Really that line is all you need to know to be able to get the setup working. On the `command:pass` event you'll need to return `success(username, yourNodeFS)`.

I immediately searched github and found https://github.com/RiptideElements/s3fs and tried to drop it in to place with something like this:

```
server.on('command:pass', (pass, success, failure) => {
  const bucketPath = 'mySuperCoolBucket';
  const s3Options = {
    region: 'us-east-1',
  };
  const fsImpl = new S3FS(bucketPath, s3Options);
  success(username, yourNodeFS)
});
```

The only problem I found was in the way that s3fs implements file permission values in its stat command: https://github.com/RiptideElements/s3fs/blob/master/lib/s3fs.js#L765. This causes nodeftpd to freak out about the file permissions.

Instead I decided, as I only needed to be able to write files, it would be simple just to write a little fs abstraction for myself. This worked nicely and it streams directly from the input to s3 in batches so it has a low memory footprint (and doesn't ever store to disk). I'll attach what you need here, but you'll need to complete the remaining methods (for directory listing, reading files etc.) as they're more than I need for my purposes.

index.js:

```
    import { FtpServer } from 'ftpd';
    import S3FS from './s3fs';
    const server = new FtpServer('0.0.0.0', {
        getInitialCwd: () => '/',
        getRoot: () => '/',
      });
    server.on('client:connected', (connection) => {
      let username = null;
      connection.on('command:user', (user, success) => {
        username = user;
      });
      connection.on('command:pass', () => {
        const fsImpl = new S3FS(username, pass);
        success(username, fsImpl);
      });
    });
    server.listen(21);
```

s3fs.js:

```
import AWS from 'aws-sdk';

import { PassThrough } from 'stream';
import MockStat from './mock_stat';

export default class s3fs {
  createReadStream() {
    throw new Error('Unimplemented');
  }

  s3() {
    return new AWS.S3();
  }

  createWriteStream(filename) {
    const stream = PassThrough();
    AWS.S3().upload({
      Bucket: 'mySuperCoolBucket',
      Key: filename,
      Body: stream,
    }, () => {});
    setTimeout(() => stream.emit('open'), 10); // hack as stream wouldn't start
    return stream;
  }

  exists(p, callback) {
    callback(null, false);
  }

  stat(p, callback) {
    callback(null, new MockStat());
  }

  lstat(p, callback) {
    this.stat(p, callback);
  }

  mkdir(p, ...callbacks) {
    callbacks.slice(-1)[0](null);
  }

  readdir(...callbacks) {
    callbacks.slice(-1)[0](null, []);
  }

  readFile(filename, ...callbacks) {
    callbacks.slice(-1)[0](new Error('Not found'));
  }

  rmdir(p, callback) {
    callback(null);
  }

  unlink(p, callback) {
    callback(null);
  }

  writeFile(filename, data, ...callbacks) {
    callbacks.slice(-1)[0](new Error('Unimplemented'));
  }
}
```

mock_stat.js:

```
export default class MockStat {
  constructor() {
    this.dev = 38;
    this.mode = 16877;
    this.nlink = 19;
    this.uid = 0;
    this.gid = 0;
    this.rdev = 0;
    this.blksize = 4096;
    this.ino = 6184580;
    this.size = 646;
    this.blocks = 0;
    const fileTime = new Date();
    this.atime = fileTime;
    this.mtime = fileTime;
    this.ctime = fileTime;
    this.birthtime = fileTime;
  }

  isFile() {
    return false;
  }

  isDirectory() {
    return true;
  }

  isBlockDevice() {
    return false;
  }

  isCharacterDevice() {
    return false;
  }

  isSymbolicLink() {
    return false;
  }

  isFIFO() {
    return false;
  }

  isSocket() {
    return false;
  }
}
```

**Comment by adamdunkley** [comment]
@erickpece Quickly, for SMB you shouldn't need any special integration at all. Just mount SMB on your system and point the base of the FTP server at its mount point using the `getRoot` config option and you should be good to go. Any FTP server will support this as long as your SMB mount transparently supports all required FS commands (which almost definitely will on *nix).

**Comment by erickpece** [comment]
@adamdunkley Thanks for providing this information.  This will help us to get started!

For SMB, it's more of a personal project.  I was looking to provide a starting path which would mount the SMB share on the fly, acting as a FTP to SMB bridge of sorts.  I'm running on macOS, which has terrible support for SMB, and it's usually pretty slow.  None of the other options I've tried have solved this, so while I was looking into FTP to S3 integration, I thought I might be able to do something similar with SMB.

**Comment by mk-pmb** [comment]
I've yet to see any samba mounting software that won't grind applications to halt if a remote host goes down before you manage to umount it. In theory, node could protect my main thread from it, but there's a limit on how many threads it can open, and I couldn't yet be bothered to research what node will do once all of its thread pool fills up with "waiting for bad samba FS implementation" threads. Make double sure to `require("nosync")` so none of your deps can accidentially do something that synchronously hits your left-over symlink from debugging.

**Comment by felipe-pereira** [comment]
@adamdunkley how did you workaround the problem of getting a success transfer command/message before the the file was actually saved on S3? (due to the async S3.upload), or it wasn't a problem in your usecase?
