### ISSUE TITLE
Error Start Application

### ISSUE THREAD

**Issue by edmsantos** [nodeftpd/nodeftpd#142]
Error start test.js

util.js:280
    throw new ERR_INVALID_ARG_TYPE('superCtor', 'Function', superCtor);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function. Received type undefined

Wich a problem???

**Comment by mk-pmb** [comment]
Please see "How to install the latest version" in https://github.com/nodeftpd/nodeftpd/issues/115. If that did not help, please add your version details.
