### ISSUE TITLE
[Windows 10]Failed Tricky Path Check during installation

### ISSUE THREAD

**Issue by ericskh2** [nodeftpd/nodeftpd#150]
I failed to install this with this tricky path error. How do I actually pass the test?
Thanks. 

npm i https://github.com/nodeftpd/nodeftpd.git --save
npm ERR! code 1
npm ERR! Command failed: git checkout HEAD
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^.txt'
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/cool-glasses.😎.txt'
npm ERR!

**Comment by mk-pmb** [comment]
Please see #115 and if that didn't solve your problems, please report your {nodejs, npm, ftpd} versions.

**Comment by ericskh02** [comment]
Still have the same error with nodejs v14.15.3, npm: '6.14.9', and 
npm install https://github.com/nodeftpd/nodeftpd/
npm ERR! code 1
npm ERR! Command failed: git checkout HEAD
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^.txt'
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/cool-glasses.😎.txt'
npm ERR!

**Comment by ericskh02** [comment]
It also happened when I clone it
![image](https://user-images.githubusercontent.com/42265526/107044758-b40cef00-67ff-11eb-8580-0a1c9ebf525a.png)

**Comment by mk-pmb** [comment]
I see, windows. I have some ideas how we could achieve windows compatibility, but those are currently blocked by #147.
Until then, to install  file systems that s, you'll need either some old version from npm, or you can try my workaround:
`npm install --save https://github.com/mk-pmb/nodeftpd.git#windows-compat-workaround-210205`

**Comment by mk-pmb** [comment]
PS: Would you mind adding your windows version in brackets in front of the thread title (e.g. `[Windows 10] Failed …`)? This would help other windows users find this thread.

**Comment by ericskh02** [comment]
Sure.
It seems your workaround still failed with the same problem.
npm install --save https://github.com/mk-pmb/nodeftpd.git#windows-compat-workaround-210205
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b windows-compat-workaround-210205 https://github.com/mk-pmb/nodeftpd.git C:\Users\Alex\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c62779d4 --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\Alex\AppData\Local\Temp\pacote-git-template-tmp\git-clone-7ef850de
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^.txt'
npm ERR! fatal: unable to checkout working tree
npm ERR! warning: Clone succeeded, but checkout failed.
npm ERR! You can inspect what was checked out with 'git status'
npm ERR! and retry with 'git restore --source=HEAD :/'
npm ERR!

**Comment by mk-pmb** [comment]
Oh, of course. When installing from the repo, npm cannot even see my file until the cloning is done. I updated the branch, please retry.

**Comment by ericskh02** [comment]
It stills showed me an error but it successfully installed. Thanks a lot!

>> npm install --save https://github.com/mk-pmb/nodeftpd.git#windows-compat-workaround-210205
npm ERR! Command failed: git checkout HEAD
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^.txt'
npm ERR! error: invalid path 'fixture/jose/tricky_paths/b\\s\l, ""q'u"o"te''; pi|p|e & ^up^/cool-glasses.😎.txt'
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alex\AppData\Roaming\npm-cache\_logs\2021-02-05T14_46_34_814Z-debug.log
+ ftpd@0.2.16
added 169 packages from 147 contributors and audited 171 packages in 12.898s
